# netlify.toml

# General build settings
[build]
  functions = "netlify/functions"
  publish = "."

# Configuration for our specific scheduled function
# This tells Netlify to run the 'build-aqi-cache' function at minute 0 of every hour.
[functions."build-aqi-cache"]
  schedule = "0 * * * *"

# Redirect rules for API proxy and single-page app routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200