# netlify.toml

# General build settings
[build]
  functions = "netlify/functions"
  publish = "."

# Ensure functions bundle and include the Blobs SDK
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

# Run the 'build-aqi-cache' function at minute 0 of every hour
[functions."build-aqi-cache"]
  schedule = "0 * * * *"

# API proxy and SPA routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
