[build]
  publish = "."
  functions = "netlify/functions"

# Pin the Node runtime used to build & run functions
[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  # (optional) include globs if you read files at runtime
  # included_files = ["some-folder/**"]
